---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisapp
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4-32bit
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redisapp
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: realtimeapp
  labels:
    app: realtime
spec:
  selector:
    matchLabels:
      app: realtime
  replicas: 4
  template:
    metadata:
      labels:
        app: realtime
    spec:
      containers:
      - name: realtimeapp
        image: gbaeke/fluxapp:1.0.0
        env:
        - name: REDISHOST
          value: "redisapp:6379"
        resources:
          requests:
            cpu: 25m
            memory: 50Mi
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 8080
  strategy:
    canary:
      stableService: realtimeapp-stable
      canaryService: realtimeapp-canary
      trafficRouting:
        nginx:
          stableIngress: gateway
      steps:
      - setWeight: 20
      - pause: 
          duration: "20s"
      - setWeight: 50
      - pause: {}
---
apiVersion: v1
kind: Service
metadata:
  name: realtimeapp-stable
  labels:
    app: realtime
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: realtime
---
apiVersion: v1
kind: Service
metadata:
  name: realtimeapp-canary
  labels:
    app: realtime
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: realtime
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
#     nginx.ingress.kubernetes.io/affinity: cookie
#     nginx.ingress.kubernetes.io/affinity-mode: persistent
spec:
  rules:
  - host: real.baeke.info
    http:
      paths:
#       - path: /
#         backend:
#           serviceName: realtimeapp-stable
#           servicePort: 80
      - path: /
        backend:
          serviceName: realtimeapp-canary
          servicePort: 80
