---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  selector:
    app: nodejs
  ports:
  - name: http
    port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-blue
  labels:
    app: nodejs
spec:
  selector:
    app: nodejs
  ports:
  - name: http
    port: 8080
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nodejs
  labels:
    version: v1
spec:
  strategy:
    blueGreen:
#       steps:
#       - setWeight: 20
#       - pause:
#           duration: "20s"
#       - setWeight: 50
#       - pause: {}
      previewService: nodejs-blue
      activeService: nodejs
      trafficRouting:
        istio:
          virtualService: 
            name: nodejs
  replicas: 4
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
        version: v1
    spec:
      containers:
      - name: nodejs
        image: sathiyabama/node-demo                                 # -v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nodejs-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nodejs
spec:
  hosts:
  - "*"
  gateways:
  - nodejs-gateway
  http:
    # - match:
    # - headers:
    #     end-user:
    #       exact: sathya
  - route:
    - destination:
        host: nodejs
      weight: 100
    - destination:
        host: nodejs-blue
      weight: 0
