apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: rollouts-demo
        image: nginx:1.21      # nginxdemos/hello:0.2, hello:plain-text
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    blueGreen: 
      activeService: rollout-bluegreen-active
      previewService: rollout-bluegreen-preview
      # trafficRouting:
      #   nginx:
      #     stableIngress: rollout-ingress
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
  labels:
    app: rollout-bluegreen
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: rollout-bluegreen
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-preview
  labels:
    app: rollout-bluegreen
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: rollout-bluegreen
  type: LoadBalancer
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: rollout-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#   -  http:
#       paths:
#       - path: /
#         backend:
#           serviceName: rollout-bluegreen-active
#           servicePort: 80
#       - path: /
#         backend:
#           serviceName: rollout-bluegreen-preview
#           servicePort: 80
          
